# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 00:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0005_auto_20150928_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='practica_desde',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2016), django.core.validators.MinValueValidator(1950)], verbose_name='\xbfDesde qu\xe9 a\xf1o practica Yoga?'),
        ),
    ]
