# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 14:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0006_auto_20160122_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='practica_desde',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1950)], verbose_name='\xbfDesde qu\xe9 a\xf1o practica Yoga?'),
        ),
    ]
