# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-02 17:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0007_auto_20171010_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='practica_desde',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2018), django.core.validators.MinValueValidator(1950)], verbose_name='\xbfDesde qu\xe9 a\xf1o practica Yoga?'),
        ),
    ]
