# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-12 16:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiros', '0008_auto_20180102_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='practica_desde',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1950)], verbose_name='\xbfDesde qu\xe9 a\xf1o practica Yoga?'),
        ),
    ]
