# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacalma', '0020_auto_20151009_1331'),
        ('lacalma', '0018_auto_20151205_1904'),
    ]

    operations = [
    ]
