# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacalma', '0022_auto_20151206_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='dia_media_baja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='reserva',
            name='dias_media_baja',
            field=models.IntegerField(default=0),
        ),
    ]
