# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacalma', '0023_auto_20171010_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='dia_alta',
            new_name='precio_fuera_temporada',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='dia_baja',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='dia_media',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='dia_media_baja',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dias_alta',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dias_baja',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dias_media',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='dias_media_baja',
        ),
        migrations.AddField(
            model_name='temporada',
            name='departamentos',
            field=models.ManyToManyField(related_name='temporadas', to='lacalma.Departamento'),
        ),
    ]
