# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacalma', '0024_auto_20181125_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptofacturable',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='precio_fuera_temporada',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='deposito_reserva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
